spring:
  application:
    name: scraping-and-ai
  ai:
    ollama:
      chat:
        options:
          model: llama3.2:latest
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper_and_ai
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
